[features]
seeds = false
skip-lint = false
[programs.localnet]
create_note = "2LFoqVKYUZEbiH6uw7egsp14FKevAyZwSyPbAUzi8EeR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/sn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
