[features]
seeds = false
skip-lint = false
[programs.localnet]
counter_example = "4qiCyVbvqgb3xz4X2SFuAUAQ7iSwrGpQsDgSyjy13vgS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/sn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
